CREATE TABLE HMEASURES (
ID integer primary key generated always as identity,
STATION VARCHAR(15) NOT NULL,
SENSOR VARCHAR(15) NOT NULL,
TIME_UTC timestamp(0),
DATA NUMERIC(7,3),
RESIDUES NUMERIC(7,3),
CONSTRAINT Hcandidate_key UNIQUE (STATION,SENSOR,TIME_UTC),
CONSTRAINT Hcons_sensor CHECK (SENSOR IN ('RADAR','PRESSURE','FLOAT'))
);